default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: root
  host: localhost

development:
  <<: *default
  database: my_api_app_development

test:
  <<: *default
  database: my_api_app_test

production:
  <<: *default
  database: my_api_app_production
  username: <%= ENV['MY_API_APP_DATABASE_USERNAME'] %>
  password: <%= ENV['MY_API_APP_DATABASE_PASSWORD'] %>
